//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServisConvert.KlijentAplikacija {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KlijentAplikacija.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaBAMToEUR", ReplyAction="*")]
        double konverzijaBAMToEUR(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaBAMToEUR", ReplyAction="*")]
        System.Threading.Tasks.Task<double> konverzijaBAMToEURAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaEURToBAM", ReplyAction="*")]
        double konverzijaEURToBAM(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaEURToBAM", ReplyAction="*")]
        System.Threading.Tasks.Task<double> konverzijaEURToBAMAsync(double a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebServisConvert.KlijentAplikacija.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebServisConvert.KlijentAplikacija.WebService1Soap>, WebServisConvert.KlijentAplikacija.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double konverzijaBAMToEUR(double a) {
            return base.Channel.konverzijaBAMToEUR(a);
        }
        
        public System.Threading.Tasks.Task<double> konverzijaBAMToEURAsync(double a) {
            return base.Channel.konverzijaBAMToEURAsync(a);
        }
        
        public double konverzijaEURToBAM(double a) {
            return base.Channel.konverzijaEURToBAM(a);
        }
        
        public System.Threading.Tasks.Task<double> konverzijaEURToBAMAsync(double a) {
            return base.Channel.konverzijaEURToBAMAsync(a);
        }
    }
}
